services:
  - react-app
  - auth
  - brownbag
  - budget
  - category
  - company
  - department
  - email
  - employee
  - feedback
  - api-gateway
  - training

environment: io

nodeEnv: production

subdomain:

sendgridKey: U0cuNTJKNG1xRW1UMEd1dTJjeFo0bmk4dy5qLWQzb191Z0VfejM0QnlQdlY2X0x0WVlDNjM4UXc0bF9zTFpnM2RReDVFCg==

redis:
  service: gateway-redis-service
  namespace: sproud-prod

mongo:
  host: .divei.mongodb.net
  user: sproud-prod
  password: 2Rh3s2l5wCSMkPod
