apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sproud-redis-volume-claim-{{ .Values.environment }}
  namespace: sproud
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage
